spring:
  datasource:
    username:
    password:
    url: jdbc:postgresql://localhost:5432/strategy

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

secret-key:

algorithm: